### ISSUE TITLE
No update?

### ISSUE THREAD

**Issue by ghost** [jgraup/advanced-custom-fields-nav-menu-field#1]
Hi, i see this plugin is so interesting. Unfortunately, i have no ability to do something about this plugin yet. Maybe you are on other business. But, would these codes get updated again? 

It would be very nice to see this great work updated

**Comment by jgraup** [comment]
I added this plugin to work with ACF 5 but the original author has since updated their version at [ACF-Nav-Menu-Field 2.0](https://github.com/Faison/ACF-Nav-Menu-Field/tree/2.0.0). You can find the official WP Plugin at [wordpress.org/plugins/advanced-custom-fields-nav-menu-field](https://wordpress.org/plugins/advanced-custom-fields-nav-menu-field/).

I don't think I've used this plugin since I added it here and I don't have any current plans to update it.
